### PR TITLE
Fix bug in LIcon not properly referencing parent container's map object

### PR DESCRIPTION
**Pull request by fernando-almeida**
The current code as is only works if the Licon is directly beneath another Vue2Leafleft component.
This fix addresses using the correct real parent already determined but not used when binding props upon mounting of the component.

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@mikeu could you review this one? Since you are the l-icon expert?

**Comment by mikeu** [comment]
@fernando-almeida thank you for this submission, it looks good to me!

@DonNicoJs I do have two questions for you before we merge this:

First, it throws an explicit error when the parent container is not found. This seems like a good practice in general, but it is different behaviour from all of the other components. Do you think we should remove that exception here for consistency, or update the other components to have this improvement?

Second—and this is not actually about the PR, just raised by looking through it—the LIcon component has for a long time now made its `parentContainer` property a reactive part of its Vue `data`, which none of the other components do I don't think. Should we also remove that while updating the LIcon here? There isn't any reason that the template should need to be able to reference that property, is there? I suppose technically that would be a breaking change if anybody _has_ written code that relies on it for some reason, though...

**Comment by DonNicoJs** [comment]
> @fernando-almeida thank you for this submission, it looks good to me!
> 
> @DonNicoJs I do have two questions for you before we merge this:
> 
> First, it throws an explicit error when the parent container is not found. This seems like a good practice in general, but it is different behaviour from all of the other components. Do you think we should remove that exception here for consistency, or update the other components to have this improvement?
> 
> Second—and this is not actually about the PR, just raised by looking through it—the LIcon component has for a long time now made its `parentContainer` property a reactive part of its Vue `data`, which none of the other components do I don't think. Should we also remove that while updating the LIcon here? There isn't any reason that the template should need to be able to reference that property, is there? I suppose technically that would be a breaking change if anybody _has_ written code that relies on it for some reason, though...

I believe we should have avoided to put it in data 😅  my mistake in not noticing it before, that being said it's better to leave it as it is right now. We should take care to not do this mistake again in the vue3 version and if we did correct it ASAP.

About the error it's true that we do not have in the codebase but I think it would offer a good developer experience

**Review by DonNicoJs — APPROVED** [review]

**Comment by DonNicoJs** [comment]
@mikeu I'll merge this, and we can take care of any followup work in a further PR!

**Pull request merged**
