### PR TITLE
map options override prop defaults

### PR DESCRIPTION
**Pull request by Machine-Maker**
I was noticing that if I put all my map options into one object, and passed that to the LMap component, the default value for the crs, center, and other props would override the value from the options object. That probably shouldn't work that way, a default overriding a set value. This should fix that.

### CODE REVIEW

**Comment by Machine-Maker** [comment]
So this is a partial solution. The issue was, you were checking the default value of the props using `instance.$options.props[propName].default`. Issue with that is that sometimes, `default` is a function that needs to be called to return the actual default value, using `instance.$options.props[propName].default.call()`. 

BUT, that only needs to happen if its a function, sometimes its not. So that is a check in the code.

Next, sometimes if you are comparing the default value and both of them are arrays. So I stringify the arrays to see if they are the same.

**Comment by DonNicoJs** [comment]
@Machine-Maker Thank you for the PR and nice catch! would you mind adding some unit tests to check the new behavior?

**Comment by DonNicoJs** [comment]
@all-contributor please add @Machine-Maker for code

**Comment by DonNicoJs** [comment]
@all-contributors please add @Machine-Maker for code

**Pull request merged**
