### PR TITLE
Fractional zoom options

### PR DESCRIPTION
**Pull request by itanka9**
See https://leafletjs.com/examples/zoom-levels/, Fractional Zoom section

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Is it necessary to have all the map options be props on LMap? You can pass all of the options in the options prop. I guess its just a matter of which ones are important enough to get their own prop rather than rely on the general "options" prop.

**Comment by DonNicoJs** [comment]
@Machine-Maker Actually we put on the props and not on `options` only the properties that we can 'make reactive' in the meaning that we have a proper setProperty function exposed by leaflet

**Comment by DonNicoJs** [comment]
@itanka9 Leaflet does not have a `setZoomDelta` method, so we can't add them to the props of the component, you can always use the `options` to pass those

**Comment by itanka9** [comment]
@DonNicoJs @Machine-Maker Thank you, guys. Does not recognize `options` prop, will use it.

**Pull request closed without merging**
