### PR TITLE
Leaflet css cdn added

### PR DESCRIPTION
**Pull request by imanaspaul**
Leaflet CSS CDN added which was missing and it required to load the map view component properly.

### CODE REVIEW

**Comment by mikeu** [comment]
Hi @imanaspaul , thanks for the contribution! May I ask, what's your reasoning behind wanting to include that link two times in the quick start, right next to each other?

The current version of the quick start already specifies to include the link under the CDN heading two lines below your change, and also later on it shows how to import the CSS in your application if using a build system such as webpack or rollup with either globally or locally imported components.

If there's a workflow you've identified in the quick start for using the library where the CSS import isn't included, then adding it is definitely a good idea. I'm just not sure at the moment that I see the need to specify it as universally for all project types as your current edit makes it.

**Comment by imanaspaul** [comment]
To contribute that, I have two reasons behind this, The first one is I have been trying to work with this package, but I had the issue about when I am working with vue-cli project it doesn't render the map properly on the webpage, but when I am working with plain HTML and CSS project it does, and it took me around 30 minutes to configure the project properly, and I found that CSS CDN link for vue-cli project has missing in the readme. So I thought why not do a pr maybe someone like me would get configure their setup easily. 
Secondly, that's my first contribution so I thought why not start with this small issue that I found.

**Comment by mikeu** [comment]
Thanks, @imanaspaul ! Starting small is definitely a great idea, not a problem at all. Welcome to the project :)

I am sorry that you had trouble with the quick start. Did you try the existing instructions to import the leaflet CSS either for [system-wide usage](https://github.com/vue-leaflet/Vue2Leaflet/tree/master/docs/quickstart#system-wide-components) or when [importing components locally](https://github.com/vue-leaflet/Vue2Leaflet/tree/master/docs/quickstart#in-your-entry-point-ie-mainjs) and they did not work for you correctly?

The reason I am asking this is that I have made many different maps with vue2-leaflet that have displayed the Leaflet maps correctly, without manually including the CSS link directly in the HTML. So I hesitate to add an instruction that implies all projects should do this, since I know that many do not have to.

However, it is also clear that there is a gap of some sort in the existing instructions if you followed them and ended up with a map that didn't display correctly, so your feedback is definitely valuable and it would be great to figure out how else we could best improve the docs so this doesn't happen again.

**Comment by imanaspaul** [comment]
> I am sorry that you had trouble with the quick start. Did you try the existing instructions to import the leaflet CSS either for [system-wide usage](https://github.com/vue-leaflet/Vue2Leaflet/tree/master/docs/quickstart#system-wide-components) or when [importing components locally](https://github.com/vue-leaflet/Vue2Leaflet/tree/master/docs/quickstart#in-your-entry-point-ie-mainjs) and they did not work for you correctly?


Exactly, whenever I try to use the component ( or importing the component ) the map is not properly rendering and after doing some research, I realize that somehow I need to insert the CSS of the leaflet.  So that was the gap I felt whenever I want to implement the map. 
Most of the time I generally used to copy and paste the instruction to configure any package inside my project. So that's the missing part I thought needs to be there in instruction.

**Comment by mikeu** [comment]
> Exactly, whenever I try to use the component ( or importing the component ) the map is not properly rendering

Hmm, that is surprising to me, I am not sure why it would be happening for you. Can you provide a link to a sample project, or a [codesandbox](https://codesandbox.io) or similar, that imports the CSS in one of the ways already described in the existing quick start documentation, but which doesn't render properly?

**Pull request closed without merging**
