### PR TITLE
Add support fo subdomains

### PR DESCRIPTION
**Pull request by imagoiq**
Here maps for example require subdomains with number: 1-4

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@imagoiq Thanks for the PR! question: why the default of `abc`? Sorry for the slow answer!

**Comment by imagoiq** [comment]
The default 'abc' come from the leaflet doc: https://leafletjs.com/reference-1.6.0.html#tilelayer-subdomain

It seems that most of the tiles provider use the 'abc' convention.

**Comment by DonNicoJs** [comment]
@imagoiq Okay clear, but this would enable subdomains by default for everyone I guess 😄 which we probably do not want, am I correct?

**Comment by imagoiq** [comment]
I didn't dive deep into the Leaflet source code, but as far as I know, subdomains are only activated if you use the `{s}` keyword in the url of your tiles.

**Comment by DonNicoJs** [comment]
@imagoiq Perfect! Thank you for the explanation!   Merging

**Pull request merged**
