### PR TITLE
fix: rework activated logic and move it to visible

### PR DESCRIPTION
**Pull request by DonNicoJs**
@C00Lzero I need to rework your Mr because it causes problem with third  party plugins, I got a report for markercluster but I suspect that is for more than one.

I move the check to 'visible' prop instead of activated, which as already a working getter, and now the check explicilty cofirm that `visible` should be `!== false` so `undefined` still add the layer

### CODE REVIEW

**Comment by C00Lzero** [comment]
oh. that's strange, since i've also using markerclusters. 

but I don't have a problem with this solution. Thanks

**Comment by C00Lzero** [comment]
ah. 
I now see the problem, why I didn't do it that way: 
If you set visible to false you won't display the Layer in the layer-chooser at all. 
Thus it's not visible (which is obviously what the options is intended to do), but also not checkable to display

**Comment by DonNicoJs** [comment]
@C00Lzero this sounds like the real bug! I'll keep you posted

**Comment by laurencei** [comment]
@DonNicoJs - I've run into this issue, and I dont see how to get around it. The original PR from @C00Lzero gives the functionality I need, but this PR has removed it?

If I use `:visible=false` in my `l-feature-group`, then the group is not an option to tick at all in the control group.

Basically - I want to have 3-4 different feature groups. By default they all start 'checked' and visible. I want one of them to be an option in the control layer, but start unchecked.

I've searched and checked everywhere, and I cant find a way to achieve it after this PR?

**Comment by pandemie** [comment]
I agree with @laurencei.

There does not seem to be a way to add a layer which is unchecked per default in the layer controls.

Can you advise, @DonNicoJs?

**Pull request merged**
