### PR TITLE
Crs switching and examples

### PR DESCRIPTION
**Pull request by itanka9**

### CODE REVIEW

**Comment by itanka9** [comment]
May be we should unite all examples about CRS into big one?

**Comment by DonNicoJs** [comment]
@itanka9 Thank you for the PR! I have a question, should we make pro4leafet a peer dependency? Also, I am not totally sure that this should be in the main repo and not in a plugin 🤔 but then overriding the functionality of crs is not easy...

Sorry for being late here, apologies. What are your thoughts?

**Comment by itanka9** [comment]
@DonNicoJs Thanks for your feedback. I don't think we need proj4leaflet to be a peer dependency, actually vue2leaflet does not depend on it and do not use it inside, all is done via composition.

About crs. Long ago in my company i've forked vue2leaflet into our codebase and now I want to get things back - make it an npm dependency, not our private (and obsolete) piece of code. Switching crs on the fly - is a feature, we need. I'm agree, that in some cases it do not work correctly (because we cannot always project one crs to another one-to-one). On the other side crs switching is a rare case, I doubt, that it creates a problems.

I may cut this PR to only the proj4leaflet example, if it will be better.

**Comment by DonNicoJs** [comment]
@itanka9 Thank you for the explanation, I was a bit out of context! now is clear, I think we can merge as it is, if for you is okay!

**Comment by itanka9** [comment]
@DonNicoJs Good news! Let's merge it.

**Comment by DonNicoJs** [comment]
@all-contributors please add @itanka9 for docs and code

**Pull request merged**
